# Generated by Django 3.1.6 on 2021-02-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='unix_timestamp',
            field=models.CharField(default='1612471618', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='alert_date_time',
            field=models.CharField(default='04/02/2021 20:46:58', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='email_date_time',
            field=models.CharField(default='04/02/2021 20:46:58', max_length=500),
        ),
    ]
